# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('patient_fhir_id', models.CharField(blank=True, default='', max_length=255)),
                ('access_key_id', models.CharField(blank=True, max_length=20)),
                ('access_key_secret', models.CharField(blank=True, max_length=40)),
                ('access_key_reset', models.BooleanField(default=False, help_text='Check this box to issue a new access key. Doing so invalidates the existing key.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
